### ISSUE TITLE
Could you include postgres in docker-compose.yml

### ISSUE THREAD

**Issue by bonelifer** [Mirio/verbacap#167]
**Is your feature request related to a problem? Please describe.**
Would be nice to have a compose file with postgres included.

**Describe the solution you'd like**
Include a version of the yml with postgres included.

**Comment by Mirio** [comment]
You can use the "demo" version file, it included all batteries and deps with the latest version: https://github.com/Mirio/verbacap/blob/develop/compose-demo.yaml

You can run it using:
```
docker compose -f compose-demo.yaml up -d
```
